### ISSUE TITLE
Compatibility with radio elements

### ISSUE THREAD

**Issue by raisen** [vollnhals/dependent-fields-rails#1]
How would you make your gem compatible with radio elements?  I have started the implementation as such:

bind:
  $inputs = $('input[type=radio]')
  $inputs.not('[data-important]').each _.partial(showOrHideDependentFieldsRadio, 0)
  $inputs.filter('[data-important]').each _.partial(showOrHideDependentFieldsRadio, 0)

showOrHideDependentFieldsRadio = (duration = 'fast') ->
  $radio = $(this)

  showOrHideFields = ->
    $this = $(this)
    showOrHide = $this.data('radio-value') == $radio.is(':checked')
    toggle($this, showOrHide, $this.data('method'), duration)

  $(".js-dependent-fields[data-radio-id=#{$radio.attr('id')}]").each showOrHideFields

The logic above isn't working though. Any thoughts?

**Comment by vollnhals** [comment]
Hello,

I can look into this tomorrow morning (Berlin time). 

Regards,
Lion

Am 10.06.2013 um 20:24 schrieb Weydson Lima notifications@github.com:

**Comment by vollnhals** [comment]
Hi,

sorry for the late reply.

I looked into this and had the following problems:
- all radio inputs in a group have different ids
- change events only fire on the radio input that is selected and not on the others

I pushed a new version of the gem that supports radio inputs.
See the README on github.

Regards,
Lion

**Comment by raisen** [comment]
Sorry for the late reply as well, working like a charm now, thank you!
