### ISSUE TITLE
Syntax error, unrecognized expression: .js-dependent-fields

### ISSUE THREAD

**Issue by nagyt234** [vollnhals/dependent-fields-rails#3]
I got the following error message:

```
Syntax error, unrecognized expression: .js-dependent-fields s[data-radio-name=q\[basket\][all_items]]
```

The problem is that only the first '[' and ']' characters are escaped in dependent-fields.js.coffee::showOrHideDependentFieldsRadio:

```
...$radio.attr('name').replace('[', '\\[').replace(']', '\\]')...
```

It should be:

```
...$radio.attr('name').replace(/\[/g, '\\[').replace(/]/g, '\\]')...
```

This expression appears twice in the function showOrHideDependentFieldsRadio. Note that ']' must not be escaped for replace.

Could you create a new gem version.

Thx.

```
```

**Comment by vollnhals** [comment]
Hi, 

thanks for the pull request. I will look into it today and will release a new gem version.

**Comment by vollnhals** [comment]
I have merged your changes and released a new gem version.
Additionally, you are now featured in the change log.

**Comment by nagyt234** [comment]
Thx
