### ISSUE TITLE
Rails 4.0 Compatibility/railties version dependency

### ISSUE THREAD

**Issue by mcbridejc** [vollnhals/dependent-fields-rails#5]
Currently won't work with Rails 4.0, simply because of the railties dependency: 

s.add_dependency "railties", "~> 3.1"

Since there is basically no ruby in this package, there is no reason it shouldn't work with rails 4.0, and in fact I have been able to do so. I've forked it for now, but I thought you might like to fix this simple issue in your repository. I'll go ahead and make a pull request. 

Thanks for the helpful gem, by the way.

**Comment by shepmaster** [comment]
Looks like this was fixed by 803aceab53d2b009fb7cb522a7b47534ce1f7c7c, should it be closed?

**Comment by vollnhals** [comment]
It was indeed fixed.
